# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_dialog-ONLY_ONE_TAB.ui'
#
# Created: Wed Jan 28 15:14:25 2015
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName(_fromUtf8("OptionsDialog"))
        OptionsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        OptionsDialog.resize(350, 330)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OptionsDialog.sizePolicy().hasHeightForWidth())
        OptionsDialog.setSizePolicy(sizePolicy)
        OptionsDialog.setMinimumSize(QtCore.QSize(350, 330))
        OptionsDialog.setMaximumSize(QtCore.QSize(350, 330))
        OptionsDialog.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        OptionsDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        OptionsDialog.setAutoFillBackground(False)
        OptionsDialog.setModal(True)
        self.optionsTabContainer = QtGui.QTabWidget(OptionsDialog)
        self.optionsTabContainer.setGeometry(QtCore.QRect(9, 9, 331, 285))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsTabContainer.sizePolicy().hasHeightForWidth())
        self.optionsTabContainer.setSizePolicy(sizePolicy)
        self.optionsTabContainer.setMinimumSize(QtCore.QSize(331, 285))
        self.optionsTabContainer.setMaximumSize(QtCore.QSize(331, 285))
        self.optionsTabContainer.setTabsClosable(False)
        self.optionsTabContainer.setObjectName(_fromUtf8("optionsTabContainer"))
        self.tab_Appearance = QtGui.QWidget()
        self.tab_Appearance.setObjectName(_fromUtf8("tab_Appearance"))
        self.fontSelectionGroup = QtGui.QGroupBox(self.tab_Appearance)
        self.fontSelectionGroup.setGeometry(QtCore.QRect(10, 10, 307, 76))
        self.fontSelectionGroup.setObjectName(_fromUtf8("fontSelectionGroup"))
        self.selectFontButton = QtGui.QPushButton(self.fontSelectionGroup)
        self.selectFontButton.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.selectFontButton.setDefault(False)
        self.selectFontButton.setObjectName(_fromUtf8("selectFontButton"))
        self.fontSelectionTextbox = QtGui.QLineEdit(self.fontSelectionGroup)
        self.fontSelectionTextbox.setEnabled(True)
        self.fontSelectionTextbox.setGeometry(QtCore.QRect(10, 32, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fontSelectionTextbox.setFont(font)
        self.fontSelectionTextbox.setReadOnly(True)
        self.fontSelectionTextbox.setObjectName(_fromUtf8("fontSelectionTextbox"))
        self.colorSelectionGroup = QtGui.QGroupBox(self.tab_Appearance)
        self.colorSelectionGroup.setGeometry(QtCore.QRect(9, 91, 307, 91))
        self.colorSelectionGroup.setAutoFillBackground(False)
        self.colorSelectionGroup.setFlat(False)
        self.colorSelectionGroup.setObjectName(_fromUtf8("colorSelectionGroup"))
        self.bgColorLabel = QtGui.QLabel(self.colorSelectionGroup)
        self.bgColorLabel.setGeometry(QtCore.QRect(20, 54, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bgColorLabel.setFont(font)
        self.bgColorLabel.setObjectName(_fromUtf8("bgColorLabel"))
        self.fgColorLabel = QtGui.QLabel(self.colorSelectionGroup)
        self.fgColorLabel.setGeometry(QtCore.QRect(21, 18, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fgColorLabel.setFont(font)
        self.fgColorLabel.setObjectName(_fromUtf8("fgColorLabel"))
        self.fgColorSelectorFrame = QtGui.QFrame(self.colorSelectionGroup)
        self.fgColorSelectorFrame.setGeometry(QtCore.QRect(116, 16, 24, 24))
        self.fgColorSelectorFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.fgColorSelectorFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fgColorSelectorFrame.setLineWidth(3)
        self.fgColorSelectorFrame.setMidLineWidth(2)
        self.fgColorSelectorFrame.setObjectName(_fromUtf8("fgColorSelectorFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fgColorSelectorFrame)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fgColorSelector = QtGui.QPushButton(self.fgColorSelectorFrame)
        self.fgColorSelector.setAutoFillBackground(False)
        self.fgColorSelector.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.fgColorSelector.setText(_fromUtf8(""))
        self.fgColorSelector.setIconSize(QtCore.QSize(16, 16))
        self.fgColorSelector.setObjectName(_fromUtf8("fgColorSelector"))
        self.horizontalLayout.addWidget(self.fgColorSelector)
        self.bgColorSelectorFrame = QtGui.QFrame(self.colorSelectionGroup)
        self.bgColorSelectorFrame.setGeometry(QtCore.QRect(116, 52, 24, 24))
        self.bgColorSelectorFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.bgColorSelectorFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.bgColorSelectorFrame.setLineWidth(3)
        self.bgColorSelectorFrame.setMidLineWidth(2)
        self.bgColorSelectorFrame.setObjectName(_fromUtf8("bgColorSelectorFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.bgColorSelectorFrame)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setMargin(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.bgColorSelector = QtGui.QPushButton(self.bgColorSelectorFrame)
        self.bgColorSelector.setAutoFillBackground(False)
        self.bgColorSelector.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.bgColorSelector.setText(_fromUtf8(""))
        self.bgColorSelector.setIconSize(QtCore.QSize(16, 16))
        self.bgColorSelector.setObjectName(_fromUtf8("bgColorSelector"))
        self.horizontalLayout_2.addWidget(self.bgColorSelector)
        self.fontPreviewLabel = QtGui.QLabel(self.tab_Appearance)
        self.fontPreviewLabel.setGeometry(QtCore.QRect(10, 182, 71, 20))
        self.fontPreviewLabel.setObjectName(_fromUtf8("fontPreviewLabel"))
        self.fontPreviewBox = QtGui.QPlainTextEdit(self.tab_Appearance)
        self.fontPreviewBox.setGeometry(QtCore.QRect(13, 200, 301, 51))
        self.fontPreviewBox.setAutoFillBackground(True)
        self.fontPreviewBox.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.fontPreviewBox.setObjectName(_fromUtf8("fontPreviewBox"))
        self.optionsTabContainer.addTab(self.tab_Appearance, _fromUtf8(""))
        self.buttonFrame = QtGui.QFrame(OptionsDialog)
        self.buttonFrame.setGeometry(QtCore.QRect(10, 300, 331, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFrame.sizePolicy().hasHeightForWidth())
        self.buttonFrame.setSizePolicy(sizePolicy)
        self.buttonFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.buttonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.buttonFrame.setLineWidth(0)
        self.buttonFrame.setObjectName(_fromUtf8("buttonFrame"))
        self.saveCancelButtons = QtGui.QDialogButtonBox(self.buttonFrame)
        self.saveCancelButtons.setGeometry(QtCore.QRect(79, 0, 151, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveCancelButtons.sizePolicy().hasHeightForWidth())
        self.saveCancelButtons.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.saveCancelButtons.setFont(font)
        self.saveCancelButtons.setOrientation(QtCore.Qt.Horizontal)
        self.saveCancelButtons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.saveCancelButtons.setCenterButtons(True)
        self.saveCancelButtons.setObjectName(_fromUtf8("saveCancelButtons"))
        self.resetButton = QtGui.QPushButton(self.buttonFrame)
        self.resetButton.setGeometry(QtCore.QRect(0, 0, 73, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        self.resetButton.setFont(font)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.bgColorLabel.setBuddy(self.bgColorSelector)
        self.fgColorLabel.setBuddy(self.fgColorSelector)
        self.fontPreviewLabel.setBuddy(self.fontPreviewBox)

        self.retranslateUi(OptionsDialog)
        self.optionsTabContainer.setCurrentIndex(0)
        QtCore.QObject.connect(self.saveCancelButtons, QtCore.SIGNAL(_fromUtf8("rejected()")), OptionsDialog.reject)
        QtCore.QObject.connect(self.saveCancelButtons, QtCore.SIGNAL(_fromUtf8("accepted()")), OptionsDialog.accept)
        QtCore.QObject.connect(self.saveCancelButtons, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), OptionsDialog.update)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)
        OptionsDialog.setTabOrder(self.optionsTabContainer, self.selectFontButton)
        OptionsDialog.setTabOrder(self.selectFontButton, self.fontSelectionTextbox)
        OptionsDialog.setTabOrder(self.fontSelectionTextbox, self.fgColorSelector)
        OptionsDialog.setTabOrder(self.fgColorSelector, self.bgColorSelector)
        OptionsDialog.setTabOrder(self.bgColorSelector, self.fontPreviewBox)
        OptionsDialog.setTabOrder(self.fontPreviewBox, self.resetButton)
        OptionsDialog.setTabOrder(self.resetButton, self.saveCancelButtons)

    def retranslateUi(self, OptionsDialog):
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Options", None))
        self.fontSelectionGroup.setTitle(_translate("OptionsDialog", "Font", None))
        self.selectFontButton.setText(_translate("OptionsDialog", "Select Font", None))
        self.colorSelectionGroup.setTitle(_translate("OptionsDialog", "Colors", None))
        self.bgColorLabel.setText(_translate("OptionsDialog", "Background: ", None))
        self.fgColorLabel.setText(_translate("OptionsDialog", "Foreground: ", None))
        self.fontPreviewLabel.setText(_translate("OptionsDialog", "Font Preview", None))
        self.optionsTabContainer.setTabText(self.optionsTabContainer.indexOf(self.tab_Appearance), _translate("OptionsDialog", "Appearance", None))
        self.resetButton.setText(_translate("OptionsDialog", "Reset", None))

